### ISSUE TITLE
webpack-cli 4.x doesn't work with a TypeScript config file

### ISSUE THREAD

**Issue by yovanoc** [webpack/webpack-cli#1135]
**Describe the bug**

Here's my webpack.config.ts : https://gist.github.com/yovanoc/cd86b8f226f45dfb465d2c2d9474862c

**What is the current behavior?**

This error happen on build:

```
$ webpack --config webpack.config.ts
⬢ webpack:  TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:118:11)
    at Module.require (internal/modules/cjs/loader.js:1016:3)
    at require (/Users/devchris/Documents/code/nodejs/project/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at /Users/devchris/Documents/code/nodejs/project/packages/cli/node_modules/webpack-cli/lib/groups/config.js:60:39
    at Array.forEach (<anonymous>)
    at ConfigGroup.requireConfig (/Users/devchris/Documents/code/nodejs/project/packages/cli/node_modules/webpack-cli/lib/groups/config.js:59:33)
    at ConfigGroup.resolveConfigFiles (/Users/devchris/Documents/code/nodejs/project/packages/cli/node_modules/webpack-cli/lib/groups/config.js:128:41)
    at ConfigGroup.run (/Users/devchris/Documents/code/nodejs/project/packages/cli/node_modules/webpack-cli/lib/groups/config.js:177:20)
    at /Users/devchris/Documents/code/nodejs/project/packages/cli/node_modules/webpack-cli/lib/webpack-cli.js:102:63
    at Array.map (<anonymous>) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

**Additional context**

```
"webpack": "^5.0.0-beta.7",
"webpack-cli": "^4.0.0-beta.1",
```

**Comment by rishabh3112** [comment]
@yovanoc provide a minimum reproducible repository to help us dig in the issue.

**Comment by yovanoc** [comment]
Ok, I will try to do that asap

**Comment by yovanoc** [comment]
just a `yarn build` here https://github.com/yovanoc/webpack-issue

**Comment by ematipico** [comment]
You need to use `ts-node` if you want to provide a TypeScript file to webpack. By default webpack doesn't understand TypeScript. You have to give webpack a configuration file that webpack is able to understand

**Comment by yovanoc** [comment]
I have it in globals. But same, if I put it in the project is doesn't work either.

**Comment by rishabh3112** [comment]
@yovanoc I haven't checked your repository yet, but #1144 might be related to your issue.

**Comment by yovanoc** [comment]
Nope, nothing fix this issue. I already read https://webpack.js.org/configuration/configuration-languages/#typescript

I think the issue is related to node13 and/or these modules versions together.

**Comment by ematipico** [comment]
I saw the repo. I you have to start `ts-node` BEFORE running webapck

**Comment by yovanoc** [comment]
You're wrong. Look at the webpack website.

**Comment by ematipico** [comment]
Great thanks!

**Comment by sriniwaz** [comment]
poda lusu

**Comment by vvni** [comment]
Did this issue not be resolved？

**Comment by yovanoc** [comment]
Not yet

**Comment by vvni** [comment]
ok.🙂

**Comment by yovanoc** [comment]
Hope it will be tackled one day 👍

**Comment by nathanielcook** [comment]
Should we rename this issue to "webpack-cli 4.x doesn't work with a TypeScript config file"?

**Comment by yovanoc** [comment]
Yeah, sounds clearer

**Comment by ematipico** [comment]
This is now fixed

**Comment by meixg** [comment]
`4.0.0-beta.2` can still get this problem.
where is the fix commit?

> This is now fixed
