### ISSUE TITLE
Bug: Error while resolving entry from config in .webpack folder

### ISSUE THREAD

**Issue by anshumanv** [webpack/webpack-cli#1937]
**Describe the bug**

Not able to find entry file when a config present in .webpack folder is used.

**What is the current behavior?**

Not able to resolve entry properly

**To Reproduce**

https://github.com/webpack/webpack-cli/issues/1843#issuecomment-706618761

**Expected behavior**

Configs in project root or `.webpack` folder should work the same.

**Screenshots**

**Please paste the results of `webpack-cli info` here, and mention other relevant information**

**Additional context**

Ref https://github.com/webpack/webpack-cli/issues/1843

**Comment by evilebottnawi** [comment]
@anshumanv I think it is fixed in master

**Comment by anshumanv** [comment]
tried a while ago on master, still exists 😞 
![image](https://user-images.githubusercontent.com/21009455/95883835-ffa31500-0d98-11eb-93e0-17f873459243.png)

**Comment by ryanclark** [comment]
I've just cloned the example repo locally and regardless of the folder being named `.webpack` or `.config`, I don't get the error seen with the latest `webpack-cli@master` (albeit not released on NPM yet)

I do however see a different error now that seems to be related to `mini-css-extract-plugin`. Will take a look.

![image](https://user-images.githubusercontent.com/7922109/96038277-ccc35480-0e5e-11eb-92f8-aeb319045187.png)

**Comment by evilebottnawi** [comment]
@ryanclark Can you send tests to ensure we will not have regressions in future

**Comment by ryanclark** [comment]
Sure thing @evilebottnawi I'm just trying to figure out what the original issue was, and what the current issue they currently have with `mini-css-extract-plugin`

I'm not sure if the error is down to the plugin because if I remove the `.css` import, I get the same error with `html-webpack-plugin`. Both are on their latest versions.

![image](https://user-images.githubusercontent.com/7922109/96039569-c3d38280-0e60-11eb-82fd-9c106f586e2f.png)

**Comment by evilebottnawi** [comment]
Two version of webpack

**Comment by ryanclark** [comment]
I only see 

```

webpack@5.0.0:
  version "5.0.0"
  resolved "https://registry.yarnpkg.com/webpack/-/webpack-5.0.0.tgz#c028b2f0c1db2322de1f4a30cc36f6e373d5a26a"
  integrity sha512-OK+Q9xGgda3idw/DgCf75XsVFxRLPu48qPwygqI3W9ls5sDdKif5Ay4SM/1UVob0w4juJy14Zv9nNv0WeyV0aA==
  dependencies:
    "@types/eslint-scope" "^3.7.0"
    "@types/estree" "^0.0.45"
    "@webassemblyjs/ast" "1.9.0"
    "@webassemblyjs/helper-module-context" "1.9.0"
    "@webassemblyjs/wasm-edit" "1.9.0"
    "@webassemblyjs/wasm-parser" "1.9.0"
    acorn "^8.0.3"
    browserslist "^4.14.3"
    chrome-trace-event "^1.0.2"
    enhanced-resolve "^5.2.0"
    eslint-scope "^5.1.0"
    events "^3.2.0"
    glob-to-regexp "^0.4.1"
    graceful-fs "^4.2.4"
    json-parse-better-errors "^1.0.2"
    loader-runner "^4.1.0"
    mime-types "^2.1.27"
    neo-async "^2.6.2"
    pkg-dir "^4.2.0"
    schema-utils "^3.0.0"
    tapable "^2.0.0"
    terser-webpack-plugin "^4.1.0"
    watchpack "^2.0.0"
    webpack-sources "^2.0.1"
```

and multiple versions of the `@types/webpack`

`yarn why webpack` also only shows one version

![image](https://user-images.githubusercontent.com/7922109/96040012-80c5df00-0e61-11eb-9522-f777639a5b92.png)

**Comment by evilebottnawi** [comment]
Please look at lock file, this problem appears only when you have two webpack versions

**Comment by ryanclark** [comment]
Can confirm, the issue laid with my setup.

Updating to `webpack@5.1.0` and using the latest `webpack-cli@master` make the example repo compile fine for me.

**Comment by evilebottnawi** [comment]
Fixed in master, tests added in previously PR
